<?php

/**
 * Copyright © PinBlooms Technology Pvt. Ltd. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
$_product = $block->getProduct();
$_brand = $block->getBrand($_product) ?? '';
$_sku = $block->getSku($_product) ?? '';

$summaryModel = $block->getReviewSummary();
$rating = [];
$_items = $block->getReviewsCollection()->getItems();
foreach ($_items as $review) {
    $rating[$review['review_id']] = round($block->getReviewRating($review['review_id']), 2);
}
$reviewCount = $summaryModel->getReviewsCount();
$reviewCount = $reviewCount ? $reviewCount : 0;

$ratingSummary = ($summaryModel->getRatingSummary()) ? $summaryModel->getRatingSummary() : 20;
// @codingStandardsIgnoreStart
?>

<script type="application/ld+json">
    {

        "@context": "https://schema.org/",
        "@type": "Product",
        "name": "<?php /* @escapeNotVerified */ echo $block->escapeQuote($block->stripTags($_product->getName())); ?>",
        "image": "<?php /* @escapeNotVerified */ echo $block->stripTags($block->getImage($_product, 'product_base_image')->getImageUrl()); ?>",
        "description": "<?php /* @escapeNotVerified */ echo $block->escapeQuote($block->stripTags($block->getDescription($_product))); ?>",
        <?php if (strlen(trim($_brand))) : ?> "brand": {
                "@type": "Brand",
                "name": "<?php echo $block->stripTags($_brand); ?>"
            },
        <?php endif; ?>
        <?php if (strlen(trim($_sku))) : ?> "sku": "<?php echo $block->stripTags($_sku); ?>",
        <?php endif; ?>
        <?php if ($reviewCount) : ?> "review": [
                <?php foreach ($_items as $review) : ?> {
                        "@type": "Review",
                        "reviewRating": {
                            "@type": "Rating",
                            "ratingValue": "<?php echo $rating[$review['review_id']]; ?>"
                        },
                        "author": {
                            "@type": "Person",
                            "name": "<?= $review['nickname']; ?>"
                        }
                    },
                <?php endforeach; ?>
            ],
            "aggregateRating": {
                "@type": "AggregateRating",
                "ratingValue": "<?php echo $ratingSummary; ?>",
                "bestRating": "100",
                "ratingCount": "20"
                "reviewCount": "<?php echo $reviewCount ?>",
            },
        <?php endif; ?> "offers": {
            "@type": "Offer",
            "priceCurrency": "<?php echo $block->getCurrencyCode() ?>",
            "url": "<?php echo $block->stripTags($block->getCurrentUrl($_product)); ?>",
            <?php if ($_product->isAvailable()) : ?> "availability": "https://schema.org/InStock",
            <?php else : ?> "availability": "https://schema.org/OutOfStock",
            <?php endif; ?> "price": "<?php echo $this->getPrice(); ?>"
        }

    }
</script>
<?php
// @codingStandardsIgnoreEnd
?>